apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: jupyter-experiment
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
